<!-- <details>
    <summary></summary>
</details> -->

## 2.4 향상된 비동기 프로그래밍 1 : 프로미스

### 2.4.1 프로미스 이해하기

콜백패턴의 문제
콜백이 조금만 중첩돼도 코드가 복잡해진다(콜백지옥)

#### 콜백지옥의 예

```js
function requestData1(callback) { 
    // ...
    callback(data); // 2
}

function requestData2(callback) {
    // ...
    callback(data) // 4
}

function onSuccess1(data) {
    console.log(data);
    requestData2(onSuccess2); // 3
}

function onSuccess2(data) { // 5
    console.log(data);
    // ...
}

requestData1(onSuccess1); // 1
```

#### 프로미스 사용 예

```js
// 프로미스 사용 시 비동기 코드를 순차적으로 작성할 수 있다.
requestData1()
    .then(data => {
        console.log(data);
        return requestData2();
    })
    .then(data => {
        console.log(data);
        //...
    })
```


<br>

#### 프로미스의 3가지 상태  
    1. 대기중(pending) : 결과를 기다리는중
    2. 이행됨(fulfilled) : 수행이 정상적으로 끝났고 결과값을 가지고 있음
    3. 거부됨(rejected) : 수행이 비정상적으로 끝났음

대기중 -> 다른 상태로 변경되면 더 이상 다른 상태로 변경되지 않는다.


#### 프로미스를 생성하는 방법 (3가지)

```js
// 1
const p1 = new Promise((resolve, reject) => {
    // ...
    resolve(data);
    // 혹은 reject('error message');
})

// 2
const p2 = Promise.reject('error message');

// 3
const p3 = Promise.resolve(param);
```

1. resolve호출 시 p1은 이행됨상태가 되고, reject 호출 시 거부됨상태가됨  
2. Promise.reject호출 시 거부됨상태의 프로미스가 반환됨.  
3. Promise.resolve호출 시 이행됨 상태의 프로미스가 반환됨

```js
// Promise.resolve의 반환값
const p1 = Promise.resolve(123);
console.log(p1 !== 123); // true

const p2 = new Promise(resolve => setTimeout(()=> resolve(10),1));
console.log(Promise.resolve(p2) === p2); // true

```

#### 프로미스 이용하기 1 : then

처리됨 상태에서 사용하는 메서드  
처리됨 상태가 되면 then메서드의 인수로 전달된 함수가 호출됨

```js
requestData().then(onResolve, onReject);
Promise.resolve(123).then(data => console.log(data));
Promise.reject('err').then(null, error => console.log(error)); // 에러발생
```

1. then은 항상 프로미스를 반환하므로 연속적으로 then메서드를 호출할 수 있다.
2. onResolve, onReject에서 프로미스를 반환하면 그 프로미스를 그대로 반환한다.
3. 내부에서 예외발생 시 then에는 거부됨 프로미스를 반환한다. 거부됨 상태에서는
     onReject가 존재하는 then을 만날때까지 이동한다.

```js
Promise.reject('err')
    .then(() => console.log('then1'))
    .then(() => console.log('then2'))
    .then(() => console.log('then3'), () => console.log('then4, error'));
    .then(() => console.log('then5'), () => console.log('then6, error'));
```
위의 경우 1,2,3번을 생략하고 바로 then4번이 실행된다.

#### 프로미스 이용하기 2 : catch  

프로미스 실행 중 발생한 예외를 처리한다.
then의 onReject와 같은 역할을 한다.

```js
// 1
Promise.reject(1).then(null, error => {
    console.log(error);
})

// 2
Promise.reject(1)
    .catch(err => {
        console.log(err);
    })
```

만약 1과 같이 구현(then에 onResolve, onReject)할 경우  
onResolve에서 발생한 에러를 onReject가 처리할 수 없어   
Unhandled promise rejection에러가 발생한다


```js
// 새로운 promise를 반환하는 catch
Promise.reject(1)
    .catch(error => {
        console.log('catch : ', error);
        return 30;
    })
    .then(data => {
        console.log(data); // 30
    })
```
catch 역시 새로운 프로미스를 반환하므로 계속해서 then으로 이어나갈 수 있다.

#### 프로미스 이용하기 3 : finally

then, catch에 이어 무조건 실행되는 메서드로  
프로미스 체인의 가장마지막에 사용되며,  
바로 앞의 then혹은 catch가 반환한 프로미스를 그대로 반환한다

```js
function requestData() {
    return fetch()
        .catch(err => console.log()) 
        .finally(() => {
            console.log('수행완료');
        })
}

```

### 2.4.2 프로미스 활용하기

#### 병렬로 처리하기 : Promise.all

비동기 함수간의 의존성이 없을 경우 병렬로 처리함으로써 속도를 향상시킬 수 있다.

```js
requestData1().then(data => console.log(data));
requestData2().then(data => console.log(data));

Promise.all([requestData1(), requestData2()])
    .then(([data1, data2]) => {
        //...
    })
```

모든 프로미스가 처리됨 상태가 되어야 처리됨 상태가 되고,  
하나라도 거부됨 상태가 된다면 거부됨 상태가 된다.


#### 가장 빨리 처리된 프로미스 가져오기 : Promise.race

```js
Promise.race([
    requestData(),
    new Promise((_, reject) => setTimeout(reject, 3000))
])
    .then(data => console.log(data))
    .catch(error => console.log(error));
```

위 예제는 3초 안에 requestData가 이행되지 않을 경우 에러를 발생시키는 코드이다

#### 프로미스를 이용한 데이터 캐싱

```js
let cachedPromise;
function getData() {
    cachedPromise = cachedPromise || requestData();
    return cachedPromise;
}

getData().then(v => conosle.log(v));
getData().then(v => conosle.log(v));
```

getData 첫 호출시에만 requestData가 실행되고, 그 이후에는 cachedPromise를 받아오게된다.

### 2.4.3 주의점

#### return

내부함수가 반환한 값이 프로미스 객체의 데이터이므로,  
return을 사용하지 않을 경우 undefined가 반환되므로 주의

#### 프로미스는 불변객체

then메서드는 기존 객체를 수정하지 않고 새로운 프로미스 객체를 만들어서 반환한다.  
이행됨 혹은 거절됨 상태가 된 프로미스를 다른 상태로 변경될 수 없다.

#### 중첩하지 않기

```js
// 1
requestData1()
    .then(result1 => {
        requestData2(result1)
            .then(result2 => {
                // ...
            })
    })

// 2
requestData1()
    .then(result1 => {
        return requestData2(result1);
    })
    .then(result2 => {
        // ...
    })

// 3 Promise.all
requestData1()
    .then(result1 => {
        return Promise.all([result1, resultData2(result1)]);
    })
    .then(([result1, result2]) => {
        // ...
    })
```
1의 경우 콜백지옥과 별로 다를게 없어진다  
중첩해서 사용해야할 경우 then 내에서 return한 후  
그 결과값을 다시 then에서 처리하도록 해야한다.
2번의 경우 3번처럼 Promise.all을 사용할수도 있다.

#### 동기코드의 예외처리

try/catch문 밖에 동기코드가 있을 경우 예외처리가되지 않으므로 주의

## 2.5 향상된 비동기 프로그래밍 2 : async / await

### 2.5.1 async await 이해하기

#### async await 함수는 프로미스를 반환

```js
async function getData() {
    return 123;
}
getData().then(data => console.log(data));

// Promise객체를 반환하면 그 프로미스를 그대로 반환함
async function getData2() {
    return Promise.resolve(123);
}

getData2().then(data => console.log(data)); // 123

// 예외 발생

async function getDataWithError() {
    throw new Error('123');
}

getDataWithError().catch(err => console.log(err));

```

#### await 키워드 사용하는 방법

await 프로미스 방식으로 사용하고  
프로미스가 완료될때까지 기다린다.

```js
function requestData(value) {
    return new Promise(resolve => {
        setTimeout(() => {
            console.log('requestData : ', value);
            resolve(value);
        }, 100);
    })
}

async function getData() {
    const data1 = await requestData(10);
    const data2 = await requestData(20);
    console.log(data1, data2);
    return [data1, data2];
}
```

### 2.5.2 async await 활용

#### 병렬실행

await키워드를 사용하면 순차적으로 실행되므로,  
서로 의존성이 없는 프로미스는 동시에 실행하는것이 효율적이다.  
프로미스를 생성과 동시에 비동기코드가 실행되므로,  
두개의 프로미스를 먼저 생성하고 await를 나중에 사용하면  
병렬로 실행하는 코드가 된다.
```js
// 미리 프로미스를 생성한 후 실행
async function getData() {
    const p1 = asyncFunc1();
    const p2 = asyncFunc2();
    const data1 = await p1;
    const data2 = await p2;
}

// Promise.all 이용
async function getData2() {
    const [data1, data2] = await Promise.all([asyncFunc1(), asyncFunc2()]);
}
```

#### 예외처리

async await는 try/catch문으로 처리해야한다.

```js
async function getData() {
    try {
        await doAsync();
        return doSync();
    } catch (err) {
        console.log(err);
    }
}
```

#### Thenable을 지원하는 async await

then메서드를 가지고있는 객체를 Thenable이라 하며,  
async await에서 사용할 수 있다

```js
class ThenableExample {
    then(resolve, reject) {
        setTimeout(() => resolve(123), 1000)
    }
}

async function asyncFunc() {
    const result = await new ThenableExample();
    console.log(result); // 123
}
```


## 2.6 템플릿 리터럴로 동적인 문자열 생성하기

#### 여러줄의 문자열 입력

```js
const msg = `
여
러
줄
`
```

#### 태그된 탬플릿 리터럴

```js
function highlight(strings, ...expressions) {
    return strings.reduce(
        (prevValue, str, i) => 
        expressions.length === i
            ? `${prevValue}${str}`
            : `${prevValue}${str}<strong>${expressions[i]}</strong>`
    , '');
}

const v1 = 10;
const v2 = 20;

highlight`a ${v1} b ${v2}`
//결과
// a <strong>10</strong> b <strong>20</strong>
```

## 2.7 실행을 멈출 수 있는 제너레이터

함수의 실행을 중간에 멈추고 재개할 수 있다.  
보통의 컬렉션과 달리 값을 미리 만들어놓지 않아 불필요하게 메모리를 소비하지 않고  
필요한 순간에 값을 계산해서 전달한다

### 2.7.1 제너레이터란

\*과 함께 정의된 함수와 반환하는 제너레이터 객체로 구성된다.

```js
function* f1() {
    yield 10;
    yield 20;
    return 'finished'
}

const gen = f1();
gen.next(); // 10
gen.next(); // 20
gen.next(); // 'finished'
```

1. 제너레이터함수는 제너레이터 객체만 반환하고 함수내부코드는 실행되지 않는다.  
2. next메서드를 실행시키면 yield키워드를 만날때까지만 실행되고 데이터 객체를 반환한다.  
3. yield키워드를 만날 경우 done은 false, 만나지 못했다면 true가 반환된다.  
    return을 만날경우 true가 되는데, 그 이후에 yield를 만나도 done은 true로 반환된다.

#### throw

```js
function* f1() {
    try {
        yield 10;
        yield 20;
    } catch(err) {
        console.log(err)
    }
}
gen.next();
gen.throw('err'); // { value : undefined, done : true }

```
throw메서드를 실행할 경우 예외가 발생한것으로 처리되므로  
catch문으로 들어가고 done은 true가 된다.


[for-in,for-of](https://jsdev.kr/t/for-in-vs-for-of/2938)


#### 반복가능하면서 반복자인 제너레이터 객체

제너레이터 객체 :  
반복가능하면서 반복자이다  
반복자 : 
- next 메서드를 가지고있다
- next 메서드는 value와 done속성값을 가진 객체를 반환한다
- done 속성값은 작업이 끝났을 때 참이된다.

반복가능(iterable) :
- Symbol.iterator 속성값으로 함수를 가지고있다( obj\[Symbol.iterator\])
- 해당 함수 호출 시 반복자를 반환한다.

```js
function* f1() {
    const gen = f1();
    // 제너레이터 객체는 반복가능한 객체이다
    console.log(gen[Symbol.iterator]() === gen) // true
}
```

### 2.7.2 제너레이터 활용

[map,filter,take](./generator.js)
[자연수집합](./infinity.js)

값이 필요한 순간에만 제너레이터 객체를 통해 다음값을 요청한다  
(지연평가 - lazy evaluation)

#### 제너레이터 함수끼리 호출하기

제너레이터 함수에서 다른 제너레이터 함수를 호출할때는 yield* 키워드를 이용한다.

[함수끼리_호출](./eachGens.js)

#### 제너레이터로 함수 데이터 전달하기

[데이터_전달](./passparam.js)

#### 협업 멀티태스킹

[협업_멀티](./multitasking.js)

#### 예외처리

[예외처리](./exception.js)
